# Generated by Django 4.2 on 2023-04-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("cookie", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(auto_now=True)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this oauth belongs to. A oauth will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="oauth",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this oauth.",
                        related_name="user_set",
                        related_query_name="oauth",
                        to="auth.permission",
                        verbose_name="oauth permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
