# Priority ascending (Lowest has highest priority)
subjects_pretty = [
    ["12Asmb", "12 Assembly"],
    ["PrivStud", "Private Study"],
    ["SInv", "Science Investigations"],
    ["Hub", "Hub Class"],
    ["External", "External Study"],
    ["Cell", "Cell"],
    ["SptRec", "Sports Recreation"],
    ["Comp", "Computing"],
    ["Art", "Art"],
    ["Biol", "Biology"],
    ["CELL", "Cell"],
    ["Chem", "Chemistry"],
    ["Comm", "Commerce"],
    ["DT", "Design Technology"],
    ["DigT", "Digital Technology"],
    ["Eng", "English"],
    ["Engi", "Engineering"],
    ["Fash", "Fashion"],
    ["Fit", "Fitness"],
    ["Food", "Food Tech"],
    ["GL", "Good Life"],
    ["Germ", "German"],
    ["Hist", "History"],
    ["Inno", "Innovate"],
    ["Just", "Justice"],
    ["Lit", "Literature"],
    ["MatL", "Living Maths"],
    ["Math", "Maths"],
    ["Medi", "Media"],
    ["Musi", "Music"],
    ["Phys", "Physics"],
    ["PDT", "Product Design"],
    ["SptL", "Sport & Lifestyle"],
    ["BM", "Business Management"],
    ["FL", "Faith & Life"],
    ["GM", "General Maths"],
    ["Geog", "Geography"],
    ["HHD", "Health & Human Development"],
    ["LegS", "Legal"],
    ["MM", "Maths Methods"],
    ["PE", "PE"],
    ["Psyc", "Psychology"],
    ["SM", "Specialist Maths"],
    ["Trad", "Texts & Traditions"],
    ["VisC", "Visual Communication"],
    ["Assembly", "Assembly"],
    ["Soft", "Software Development"],
    ["CS", "Christian Studies"],
    ["Chin", "Chinese"],
    ["DesT", "Design Technology"],
    ["Dram", "Drama"],
    ["GS", "General Studies"],
    ["Link", "Link"],
    ["Sci", "Science"],
    ["SptBu", "Sport (Burrows)"],
    ["SptCo", "Sport (Cooper)"],
    ["SptCu", "Sport (Cuthbert)"],
    ["SptFl", "Sport (Flynn)"],
    ["Anim", "Animal Husbandry"],
    ["Code", "Coding"],
    ["DigT", "Digital Technology"],
    ["Game", "Game Sense"],
    ["Huma", "Humanities"],
    ["MInv", "Maths Investigation"],
    ["ComL", "ComLife"],
    ["Elec", "Electronics"],
    ["OuEd", "Outdoor Education"],
    ["HG", "Homegroup"],
    ["PrivStud", "Private Study"],
    ["VETAnim", "Animals & Learning"],
    ["Farm", "Farm"],
    ["Acc", "Accounting"],
    ["VSV", "VSV"],
    ["Beyo", "Beyond the Pages"],
    ["FM", "Foundation Maths"],
]
subjects_pretty.reverse()
