weathercodes = {
    0: {"message": "Clear sky", "icon": "clear_day"},
    1: {"message": "Mainly clear sky", "icon": "clear_day"},
    2: {"message": "Partly cloudy", "icon": "partly_cloudy_day"},
    3: {"message": "Overcast", "icon": "cloudy"},
    45: {"message": "Fog", "icon": "foggy"},
    48: {"message": "Fog", "icon": "foggy"},
    51: {"message": "Light drizzle", "icon": "rainy_snow"},
    53: {"message": "Moderate drizzle", "icon": "rainy_light"},
    55: {"message": "Heavy drizzle", "icon": "rain_heavy"},
    56: {"message": "Light freezing drizzle", "icon": "rainy_snow"},
    57: {"message": "Heavy freezing drizzle", "icon": "rain_heavy"},
    61: {"message": "Light rain", "icon": "rainy_snow"},
    63: {"message": "Moderate rain", "icon": "rainy_light"},
    65: {"message": "Heavy rain", "icon": "rain_heavy"},
    66: {"message": "Light freezing rain", "icon": "rainy_snow"},
    67: {"message": "Heavy freezing rain", "icon": "rain_heavy"},
    80: {"message": "Light showers", "icon": "rainy_snow"},
    81: {"message": "Moderate showers", "icon": "rainy_light"},
    82: {"message": "Heavy showers", "icon": "rain_heavy"},
    95: {"message": "Thundering", "icon": "thunderstorm"},
    97: {"message": "Heavily thundering", "icon": "thunderstorm"},
    96: {"message": "Thundering & light hail", "icon": "thunderstorm"},
    99: {"message": "Thundering & heavy hail", "icon": "thunderstorm"},
    # We ain't gonna need these, but its documented
    71: {"message": "Slight snow", "icon": ""},
    73: {"message": "Moderate snow", "icon": ""},
    75: {"message": "Heavy snow", "icon": ""},
    85: {"message": "Light snow showers", "icon": ""},
    86: {"message": "Heavy snow showers", "icon": ""},
}
